name: test

on:
  pull_request:
    branches: ['main']
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'README.md'
      # - ".github/workflows/**"
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run app
        run: |
          uvicorn main:app &
          pid=$!
          sleep 10
          if ps -p $pid > /dev/null; then
            echo "main.py started successfully"
            kill $pid
          else
            echo "main.py failed to start"
            exit 1
          fi
      - name: Run tests
        run: |
          PYTHONPATH=. pytest
